development:
  adapter: postgresql
  encoding: utf8
  database: bonobos_project_dev
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: bonobos_project_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: bonobos_project_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
