# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ec66e5e86df16b62b5eae90f55d56eabd6fbfe1b40ba307b72ede7542f6176682f627dc986dad2883da383f114bfa5eb7d6fa7570b7a4cae3ef4bc9aeced5ef

test:
  secret_key_base: 517ba287542cbbb0f68e3918cd08c90c71abdd525c384ea6e1cd023208de910c8c18e9eba24821596495cda9a8f5b2ba3f9858fcd07f1e21ecd9c98148d3a987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
